---
version: 3
 
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest

dependencies:
  ansible_core:
    package_pip: ansible-core==2.14.4
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python:
    - PyGithub
  
  
    

  
options:
  package_manager_path: /usr/bin/microdnf
  


 


    
  