- name: Deploy application
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
   
        


    - name: Create Application from template
      ansible.builtin.template:
        src: ../templates/argocd_app.j2
        dest: "/tmp/application.yaml"

    - name: Create ArgoCD application
      ansible.builtin.command: oc create -f /tmp/application.yaml -n openshift-gitops --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
      register: output

    