- name: Deploy application
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
   
        


    - name: Create Application from template
      ansible.builtin.template:
        src: ../templates/argocd_app.j2
        dest: "/tmp/application.yaml"

     
     

    #- name: Login to OpenShift
    #  ansible.builtin.shell: oc login --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) https://kubernetes.default.svc --insecure-skip-tls-verify
    #  register: output

    - name: Create ArgoCD application
      ansible.builtin.command: oc create -f /tmp/application.yaml -n openshift-gitops 
      register: output

    