- name: Deploy application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python
    github_repo: "myrepo"
    tower_job_id: "69"
    namespace_name: myapp
  vars_files: 
    - vault-token.yml 
  tasks:
    - name: Create a Github repository
      community.general.github_repo:
        access_token: "{{ access_token }}"
        name: "{{ github_repo }}"
        description: "Just for fun"
        private: false
        state: absent
        force_defaults: true
      register: result